### DISCUSSION TITLE
request status 302 and response header `Content-Type: text/html`

### DISCUSSION THREAD

**Discussion by lete114** [deta/space-docs#107] [Q&A] [answered]
Why does the request become 302 and the response header becomes `Content-Type: text/html`?
![image](https://github.com/deta/space-docs/assets/48512251/e87ddd2c-660b-4289-bdb7-7174167b3048)

**Comment by lete114** [comment]
```js
fetch('https://getuserip-1-k6154315.deta.app/').then((r)=>{
    console.log(r.ok)
    return r.text()
}).then(console.log)
```

**Comment by lete114** [comment]
Spacefile
```yml
# Spacefile Docs: https://go.deta.dev/docs/spacefile/v0
v: 0
micros:
  - name: get-user-ip
    src: .
    engine: nodejs16
    primary: true
    run: node index.js
    dev: node index.js
```
