### DISCUSSION TITLE
fail to push code: output size limit exceeded: 0.00 MB > 262.14 MB ?

### DISCUSSION THREAD

**Discussion by lihugang** [deta/space-docs#139] [Q&A] [answered]
![Screenshot 2023-06-26 170722](https://github.com/deta/space-docs/assets/94808542/6e81b5bc-faa4-4676-8304-44547de9ebeb)
I'm using `nuxt` to build my project, however, when I pushed my codes, I met this error. (It seemed that `engine = nuxt` went wrong so I set the `engine` to the `custom`, the following is my Spacefile:
```yaml
# Spacefile Docs: https://go.deta.dev/docs/spacefile/v0
v: 0
micros:
  - name: copilot
    src: ./
    engine: custom
    primary: true
    public: true
    commands:
      - pnpm install
      - pnpm build
    run: /usr/bin/env node .output/server/index.mjs
```
)

How can I do to deal with it? Could you help me? I am always thankful for your helping.
